In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
raw_dataset=pd.read_csv("DadasBI3D.csv",sep=",")

In [ ]:
DadasBI3D = raw_dataset.copy()
DadasBI3D.head()


Well   Latitude  Longitude   Depth_m    BI
0  ABDULAZIZ-1  38.345084   39.805726   2740.0  0.27
1  ABDULAZIZ-1  38.345084   39.805726   2750.0  0.49
2  ABDULAZIZ-1  38.345084   39.805726   2760.0  0.47
3  ABDULAZIZ-1  38.345084   39.805726   2780.0  0.56
4  ABDULAZIZ-1  38.345084   39.805726   2790.0  0.23

In [ ]:
DadasBI3D.describe()

Latitude  Longitude       Depth_m          BI
count  159.000000  159.000000   159.000000  159.000000
mean    37.821512   40.383201  2859.432075    0.568302
std      0.412799    0.617857   396.698621    0.168753
min     37.229614   39.720608  2370.000000    0.230000
25%     37.287216   39.803005  2423.600000    0.435000
50%     38.003842   40.671948  2870.000000    0.560000
75%     38.120595   40.852749  3070.000000    0.685000
max     38.345084   41.482876  3735.000000    0.970000

In [ ]:
DadasBI3D.shape

(159, 5)

In [ ]:
x= DadasBI3D.iloc[:, 1].values
y=DadasBI3D.iloc[:, 2].values
z = DadasBI3D.iloc[:, 3].values
colors= DadasBI3D.iloc[:, 4].values
sizes= DadasBI3D.iloc[:, 4].values*3

In [ ]:
x

array([38.345084, 38.345084, 38.345084, 38.345084, 38.345084, 38.345084,
       38.345084, 38.345084, 38.345084, 38.345084, 38.345084, 38.345084,
       38.345084, 38.345084, 38.345084, 38.345084, 38.345084, 38.120595,
       38.120595, 38.120595, 38.120595, 38.120595, 38.120595, 38.120595,
       38.120595, 38.120595, 38.120595, 38.120595, 38.120595, 38.120595,
       38.120595, 38.149422, 38.149422, 38.149422, 38.149422, 38.149422,
       38.149422, 38.149422, 38.149422, 38.149422, 38.149422, 38.149422,
       38.149422, 38.149422, 38.149422, 38.149422, 38.149422, 38.149422,
       38.149422, 38.149422, 38.149422, 37.229614, 37.229614, 37.229614,
       37.229614, 37.229614, 37.229614, 37.229614, 37.229614, 37.229614,
       37.229614, 37.229614, 37.229614, 37.229614, 37.229614, 37.229614,
       37.229614, 37.229614, 37.229614, 38.086555, 38.086555, 38.086555,
       38.086555, 38.086555, 38.086555, 38.086555, 38.017136, 38.017136,
       38.017136, 38.017136, 38.017136, 38.017136, 

In [ ]:
y

array([39.805726, 39.805726, 39.805726, 39.805726, 39.805726, 39.805726,
       39.805726, 39.805726, 39.805726, 39.805726, 39.805726, 39.805726,
       39.805726, 39.805726, 39.805726, 39.805726, 39.805726, 39.765326,
       39.765326, 39.765326, 39.765326, 39.765326, 39.765326, 39.765326,
       39.765326, 39.765326, 39.765326, 39.765326, 39.765326, 39.765326,
       39.765326, 39.858795, 39.858795, 39.858795, 39.858795, 39.858795,
       39.858795, 39.858795, 39.858795, 39.858795, 39.858795, 39.858795,
       39.858795, 39.858795, 39.858795, 39.858795, 39.858795, 39.858795,
       39.858795, 39.858795, 39.858795, 41.482876, 41.482876, 41.482876,
       41.482876, 41.482876, 41.482876, 41.482876, 41.482876, 41.482876,
       41.482876, 41.482876, 41.482876, 41.482876, 41.482876, 41.482876,
       41.482876, 41.482876, 41.482876, 39.790732, 39.790732, 39.790732,
       39.790732, 39.790732, 39.790732, 39.790732, 39.803005, 39.803005,
       39.803005, 39.803005, 39.803005, 39.803005, 

In [ ]:
z

array([2740. , 2750. , 2760. , 2780. , 2790. , 2800. , 2810. , 2820. ,
       2830. , 2840. , 2844. , 2850. , 2860. , 2870. , 2874. , 2880. ,
       2890. , 2970. , 2980. , 2990. , 3000. , 3010. , 3020. , 3030. ,
       3040. , 3050. , 3060. , 3070. , 3080. , 3090. , 3100. , 2900. ,
       2910. , 2920. , 2930. , 2940. , 2950. , 2960. , 2970. , 2980. ,
       2990. , 3000. , 3010. , 3020. , 3030. , 3040. , 3050. , 3060. ,
       3070. , 3080. , 3090. , 2820. , 2830. , 2840. , 2844. , 2853. ,
       2854. , 2856. , 2860. , 2866. , 2870. , 2874. , 2878. , 2880. ,
       2886. , 2890. , 2900. , 2902. , 2910. , 2490. , 2520. , 2540. ,
       2570. , 2600. , 2620. , 2640. , 3216. , 3220. , 3232. , 3246. ,
       3260. , 3284. , 3308. , 3328. , 3334. , 3340. , 3360. , 3230. ,
       3240. , 3246. , 3252. , 3262. , 3274. , 3284. , 3290. , 3306. ,
       3320. , 2371.1, 2372.1, 2372.7, 2379.4, 2380.3, 2381.3, 2382.5,
       2383.5, 2384.4, 2385.3, 2386.4, 2387.9, 2388.2, 2390.5, 2390.9,
      

In [ ]:
colors

array([0.27, 0.49, 0.47, 0.56, 0.23, 0.56, 0.23, 0.58, 0.6 , 0.56, 0.54,
       0.56, 0.54, 0.46, 0.51, 0.6 , 0.36, 0.69, 0.89, 0.58, 0.72, 0.72,
       0.58, 0.57, 0.73, 0.48, 0.59, 0.53, 0.63, 0.65, 0.69, 0.58, 0.48,
       0.58, 0.53, 0.48, 0.56, 0.61, 0.49, 0.56, 0.51, 0.66, 0.49, 0.45,
       0.54, 0.57, 0.55, 0.56, 0.49, 0.49, 0.62, 0.82, 0.78, 0.68, 0.62,
       0.67, 0.72, 0.66, 0.76, 0.76, 0.81, 0.86, 0.91, 0.84, 0.75, 0.9 ,
       0.91, 0.88, 0.77, 0.69, 0.33, 0.27, 0.81, 0.83, 0.34, 0.73, 0.77,
       0.73, 0.56, 0.74, 0.73, 0.27, 0.59, 0.31, 0.26, 0.24, 0.33, 0.72,
       0.38, 0.61, 0.55, 0.52, 0.52, 0.78, 0.34, 0.61, 0.33, 0.6 , 0.52,
       0.59, 0.65, 0.59, 0.8 , 0.5 , 0.63, 0.41, 0.41, 0.88, 0.9 , 0.67,
       0.97, 0.93, 0.72, 0.53, 0.38, 0.41, 0.39, 0.39, 0.49, 0.67, 0.44,
       0.47, 0.43, 0.42, 0.51, 0.37, 0.36, 0.46, 0.41, 0.34, 0.41, 0.43,
       0.42, 0.39, 0.38, 0.76, 0.44, 0.37, 0.64, 0.39, 0.62, 0.47, 0.66,
       0.4 , 0.32, 0.83, 0.78, 0.83, 0.43, 0.65, 0.

In [ ]:
sizes

array([ 5.4,  9.8,  9.4, 11.2,  4.6, 11.2,  4.6, 11.6, 12. , 11.2, 10.8,
       11.2, 10.8,  9.2, 10.2, 12. ,  7.2, 13.8, 17.8, 11.6, 14.4, 14.4,
       11.6, 11.4, 14.6,  9.6, 11.8, 10.6, 12.6, 13. , 13.8, 11.6,  9.6,
       11.6, 10.6,  9.6, 11.2, 12.2,  9.8, 11.2, 10.2, 13.2,  9.8,  9. ,
       10.8, 11.4, 11. , 11.2,  9.8,  9.8, 12.4, 16.4, 15.6, 13.6, 12.4,
       13.4, 14.4, 13.2, 15.2, 15.2, 16.2, 17.2, 18.2, 16.8, 15. , 18. ,
       18.2, 17.6, 15.4, 13.8,  6.6,  5.4, 16.2, 16.6,  6.8, 14.6, 15.4,
       14.6, 11.2, 14.8, 14.6,  5.4, 11.8,  6.2,  5.2,  4.8,  6.6, 14.4,
        7.6, 12.2, 11. , 10.4, 10.4, 15.6,  6.8, 12.2,  6.6, 12. , 10.4,
       11.8, 13. , 11.8, 16. , 10. , 12.6,  8.2,  8.2, 17.6, 18. , 13.4,
       19.4, 18.6, 14.4, 10.6,  7.6,  8.2,  7.8,  7.8,  9.8, 13.4,  8.8,
        9.4,  8.6,  8.4, 10.2,  7.4,  7.2,  9.2,  8.2,  6.8,  8.2,  8.6,
        8.4,  7.8,  7.6, 15.2,  8.8,  7.4, 12.8,  7.8, 12.4,  9.4, 13.2,
        8. ,  6.4, 16.6, 15.6, 16.6,  8.6, 13. , 13

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import ipywidgets as widgets
from ipywidgets import interactive
from IPython.display import display



# İnteraktif işlev

def plot_3d_scatter(elev, azim, zoom, theta):
    fig = plt.figure(figsize=(25, 10))
    ax = fig.add_subplot(111, projection='3d')

    ax.scatter(x, y, z, c=colors, cmap='jet')
    cbar = plt.colorbar(ax.scatter(x, y, z, c=colors, cmap='jet'))
    cbar.set_label('BI')

    ax.view_init(elev=elev, azim=azim)
    ax.set_xlabel('Latitude')
    ax.set_ylabel('Longitude')
    ax.set_zlabel('Depth_m')
    ax.dist = zoom  # Zoom ayarı
    ax.azim = theta  # Maus ile çevirme
    plt.show()

# İnteraktif widget'ı oluşturma
elev_slider = widgets.IntSlider(min=0, max=180, value=30, description='Elevation:')
azim_slider = widgets.IntSlider(min=0, max=360, value=30, description='Azimuth:')
zoom_slider = widgets.FloatSlider(min=1, max=10, value=5, description='Zoom:')
theta_slider = widgets.IntSlider(min=0, max=360, value=30, description='Theta:')
interactive_plot = interactive(plot_3d_scatter, elev=elev_slider, azim=azim_slider, zoom=zoom_slider, theta=theta_slider)
# Adjust font size
plt.rc('font', size=12)
# Widget'ı görüntüleme
display(interactive_plot)

interactive(children=(IntSlider(value=30, description='Elevation:', max=180), IntSlider(value=30, description=…